version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: workerdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
