version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - devdojo_maratona_data:/var/lib/mysql

volumes:
    devdojo_maratona_data:


